SAMPLES_GROUP = "samples"
LIDAR_GROUP = "lidar"
CAMERA_GROUP = "camera"
TRANSFORMS_GROUP = "transforms"

TIMESTAMP_DATASET_PATH = SAMPLES_GROUP + "/timestamps"
CHUNK_IDS_DATASET_PATH = SAMPLES_GROUP + "/chunk_ids"
LIDAR_DATA_DATASET_PATH = LIDAR_GROUP + "/data"
LIDAR_OFFSETS_DATASET_PATH = LIDAR_GROUP + "/offsets"
LIDAR_COUNTS_DATASET_PATH = LIDAR_GROUP + "/counts"
CAMERA_IMAGES_DATASET_PATH = CAMERA_GROUP + "/images"

INITIAL_LIDAR_CAPACITY = 1000000
DATA_COMPRESSION_METHOD = "lzf"

NUM_SAMPLES_ATTRIBUTE = "num_samples"
LIDAR_POINT_OFFSET_ATTRIBUTE = "lidar_point_offset"

CAMERA_K_MATRIX_ATTRIBUTE = "camera_k"
CAMERA_D_MATRIX_ATTRIBUTE = "camera_d"
CAMERA_R_MATRIX_ATTRIBUTE = "camera_r"
CAMERA_P_MATRIX_ATTRIBUTE = "camera_p"
DISTORTION_MODEL_ATTRIBUTE = "distortion_model"
CAMERA_WIDTH_ATTRIBUTE = "camera_width"
CAMERA_HEIGHT_ATTRIBUTE = "camera_height"

HDF5_WRITE_BATCH_SIZE = 100
