name: Style

on:
  push:
    paths:
      - "mcap2hdf5/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install package with dev dependencies
        run: uv sync --python 3.12 --extra dev

      - name: Lint with ruff
        run: uv run ruff check .
